trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - releases/*

jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'

      - bash: make package

  - job: Publish
    dependsOn:
      - Build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/releases/')) # Only publish on tags
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'

      - bash: make publish
        displayName: Publish Package to PyPi
        env:
          PYPI_USERNAME: $(PYPI_USERNAME)
          PYPI_PASSWORD: $(PYPI_PASSWORD)
